Revert "Added gizmos but fatal error C1189: #error:  Please '#define IMGUI_DEFINE_MATH_OPERATORS' _BEFORE_ including imgui.h!"
This reverts commit 0a709d7a84a3ad6d12c40efb400233729879cc87.